# Configuration file for testing on windows via tea-CI

build:
  image: teaci/msys32
  shell: mingw32
  pull: true
  commands:
    - git clone git://github.com/astropy/ci-helpers.git
    - cmd ci-helpers\\appveyor\\setup_conda.sh
    - python setup.py build
    - python setup.py install --user
    - git clone git://github.com/phoebe-project/phoebe1.git
    - cd phoebe1\\phoebe-lib
    - cmd configure
    - make
    - make install
    - cd..
    - cd phoebe-py
    - python setup.py build
    - python setup.py install --user
    - cd..
    - cd..
    - cp tests/travis/phoebe.config ~/.phoebe-svn/
    - git clone git://github.com/phoebe-project/photodynam.git
    - cd photodynam
    - make
    - cd..
    - nosetests -v -s -d -w tests\\nosetests\\;